services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/backend/Dockerfile
      args:
        USER_ID: ${UID:-1000}
    container_name: backend
    hostname: backend
    command: sleep infinity
    ports:
      - 8080:8080
    environment:
      AIRONE_MYSQL_MASTER_URL: "mysql://airone:password@mysql:3306/airone?charset=utf8mb4"
      AIRONE_ELASTICSEARCH_URL: "elasticsearch://airone:password@elasticsearch:9200/airone"
      AIRONE_RABBITMQ_URL: "amqp://guest:guest@rabbitmq//"
    volumes:
      - .:/workspace/airone/

  frontend:
    build:
      dockerfile: .devcontainer/frontend/Dockerfile
      args:
        USER_ID: ${UID:-1000}
    container_name: frontend
    hostname: frontend
    command: sleep infinity
    volumes:
      - .:/workspace/airone/

  mysql:
    platform: linux/x86_64
    image: mysql:5.7.34
    container_name: mysql
    hostname: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      discovery.type: "single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  rabbitmq:
    image: rabbitmq:3.8.19-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    labels:
      name: rabbitmq1

volumes:
  mysql:
    driver: local
