[tool.black]
line-length = 100

[tool.mypy]
allow_untyped_globals = true
follow_imports = "silent"
ignore_missing_imports = true

[tool.ruff]
# Pyflakes (F), pycodestyle (E, W), isort (I)
select = ["E", "F", "I", "W"]
line-length = 100
extend-exclude = ["./*/migrations", "manage.py", "./node_modules"]

[tool.ruff.per-file-ignores]
"./airone/tests/test_elasticsearch.py" = ["E501"]

[tool.coverage.run]
parallel = true
concurrency = ["multiprocessing"]
