name: Build core (Python / Django)

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "**/*.py"
      - "templates/**/*.html"
      - ".github/workflows/build-core.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get install libldap2-dev libsasl2-dev libxmlsec1-dev libmysqlclient-dev pkg-config
      - name: Install dependencies
        run: |
          python3 -m venv virtualenv
          . virtualenv/bin/activate
          pip install --upgrade pip
          pip install tox
      - name: staticchecks
        env:
          TOXENV: "staticchecks"
        run: |
          . virtualenv/bin/activate
          tox

  python311:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3.8.19-management
        ports:
          - 5672:5672
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: -Xms512m -Xmx512m
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python3 -m venv virtualenv
          . virtualenv/bin/activate
          pip install --upgrade pip
          pip install tox
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '5.7'
          user: airone
          password: password
          root-password: password
          my-cnf: |
            [mysqld]
            character-set-server=utf8
            collation-server=utf8_general_ci
            default-storage-engine=innodb
        env:
          MYSQL_DATABASE: airone
      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libldap2-dev libsasl2-dev libxmlsec1-dev libmysqlclient-dev default-mysql-client libmysqlclient20
      - name: Grant permission for airone user to be able to manipulate multiple databases (airone and test_airone)
        run: |
          mysql -uroot -h127.0.0.1 -ppassword -e "GRANT ALL ON *.* to airone@'%' IDENTIFIED BY 'password'"
      - name: test
        env:
          TOXENV: "py311"
        run: |
          . virtualenv/bin/activate
          tox
      # TODO set CODECOV_TOKEN
      # - name: Coverage
      #   run: |
      #     curl -Os https://uploader.codecov.io/latest/linux/codecov
      #     chmod +x codecov
      #     ./codecov -t ${CODECOV_TOKEN}
