name: Release AirOne APIv2 client npm package to GitHub npm Registry

on:
  pull_request:
    types: [labeled]
    paths:
      - '**/api_v2/**/*.py'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ github.event.label.name == 'release-apiv2-client' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get install libldap2-dev libsasl2-dev libxmlsec1-dev libmysqlclient-dev pkg-config
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: venv
        run: |
          python3 -m venv virtualenv
          source virtualenv/bin/activate
          pip install pip --upgrade
          pip install -r requirements.txt
      # NOTE why is it needed? if missing, spectacular fails because of "no module named custom_view.api_v2"
      - name: dummy custom_view
        run: |
          mkdir -p custom_view/api_v2
          echo "urlpatterns = []" > custom_view/api_v2/urls.py
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: generate client
        run: |
          npm ci
          npm run generate:client
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ./apiclient/typescript-fetch
